
version: '3'
services:
  phpreport-app:
    build: .
    image: igalia/phpreport
    container_name: phpreport-app
    volumes:
      - phpreport-data:/var/lib/postgresql
    restart: always
    ports: 
      - '80:80'

volumes:
  phpreport-data: