"""Add calculated field to task table

Revision ID: 2a20fa1bde50
Revises: 6a1ad39b566d
Create Date: 2024-01-09 11:15:22.286210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a20fa1bde50'
down_revision = '6a1ad39b566d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("task_total_minutes", sa.Integer(), sa.Computed("_end - init")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'task_total_minutes')
    # ### end Alembic commands ###
