"""Add column to journey history

Revision ID: 2ac6108453f3
Revises: 2795e5409fb5
Create Date: 2024-01-05 10:07:17.850610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ac6108453f3'
down_revision = '2795e5409fb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("journey_history", sa.Column("yearly_expected_and_vacation", postgresql.JSONB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("journey_history", "yearly_expected_and_vacation")
    # ### end Alembic commands ###
