"""Increase username length

Revision ID: 3721dd962b84
Revises: b7cbb5c2b970
Create Date: 2023-09-11 11:18:35.529329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3721dd962b84"
down_revision = "b7cbb5c2b970"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("usr", "login", type_=sa.String(length=100))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("usr", "login", type_=sa.String(length=20))
    # ### end Alembic commands ###
