"""Add calculation functions

Revision ID: 6a1ad39b566d
Revises: cf4f31d5cd2d
Create Date: 2024-01-05 11:07:57.026492

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger
from db.functions.get_workday_count import get_workday_count
from db.functions.get_vacation_for_period import get_vacation_for_period

# revision identifiers, used by Alembic.
revision = "6a1ad39b566d"
down_revision = "cf4f31d5cd2d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_entity(get_workday_count)
    op.create_entity(get_vacation_for_period)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    get_workday_count = PGFunction(
        schema="public",
        signature="get_workday_count(start_date date, end_date date)",
        definition="# ",
    )
    op.drop_entity(get_workday_count)
    get_vacation_for_period = PGFunction(
        schema="public",
        signature="get_vacation_for_period(start_date date, end_date date, capacity numeric)",
        definition="# ",
    )
    op.drop_entity(get_vacation_for_period)
    # ### end Alembic commands ###
