"""Add function for project summaries

Revision ID: cd28ca502f89
Revises: 2a20fa1bde50
Create Date: 2024-01-09 11:56:53.889112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic_utils.pg_function import PGFunction
from db.functions.get_user_project_summaries import get_user_project_summaries

# revision identifiers, used by Alembic.
revision = 'cd28ca502f89'
down_revision = '2a20fa1bde50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_entity(get_user_project_summaries)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    get_user_project_summaries = PGFunction(
        schema="public",
        signature="get_user_project_summaries(user_id int, current date)",
        definition="# "
    )
    op.drop_entity(get_user_project_summaries)
    # ### end Alembic commands ###
