ALTER TABLE usr ADD CONSTRAINT unique_usr_login UNIQUE (login);
ALTER TABLE task ADD CONSTRAINT unique_task_usr_time UNIQUE (usrid, init, _date);
ALTER TABLE sector ADD CONSTRAINT unique_sector_name UNIQUE (name);
ALTER TABLE user_group ADD CONSTRAINT unique_user_group_name UNIQUE (name);
ALTER TABLE area ADD CONSTRAINT unique_area_name UNIQUE (name);
ALTER TABLE city ADD CONSTRAINT unique_city_name UNIQUE (name);
ALTER TABLE common_event ADD CONSTRAINT unique_common_event_city_date UNIQUE (cityid, _date);
ALTER TABLE custom_event ADD CONSTRAINT unique_custom_event_user_date UNIQUE (usrid, _date);
ALTER TABLE extra_hour ADD CONSTRAINT unique_extra_hour_user_date UNIQUE (usrid, _date);
ALTER TABLE city_history ADD CONSTRAINT unique_city_history_user_date UNIQUE (usrid, init_date);
ALTER TABLE area_history ADD CONSTRAINT unique_area_history_user_date UNIQUE (usrid, init_date);
ALTER TABLE hour_cost_history ADD CONSTRAINT unique_hour_cost_history_user_date UNIQUE (usrid, init_date);
ALTER TABLE journey_history ADD CONSTRAINT unique_journey_history_user_date UNIQUE (usrid, init_date);
ALTER TABLE project_schedule ADD CONSTRAINT unique_project_schedule_user_project_date UNIQUE (usrid, projectid, init_year, init_week);
ALTER TABLE iteration ADD CONSTRAINT unique_iteration_project_name UNIQUE (projectId, name);
ALTER TABLE story ADD CONSTRAINT unique_story_iteration_name UNIQUE (iterationId, name);
ALTER TABLE task_story ADD CONSTRAINT unique_task_story_story_name UNIQUE(storyId, name);
ALTER TABLE module ADD CONSTRAINT unique_module_project_name UNIQUE (projectId, name);
ALTER TABLE section ADD CONSTRAINT unique_section_iteration_name UNIQUE (moduleId, name);
ALTER TABLE task_section ADD CONSTRAINT unique_task_section_section_name UNIQUE(sectionId, name);
