name: Build images

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: igalia/phpreport/frontend
  API_IMAGE_NAME: igalia/phpreport/api

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker (frontend)
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
      - name: Build and push Docker image (frontend)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/prod.frontend.Dockerfile
          push: true
          pull: true
          tags: |
            ghcr.io/igalia/phpreport/frontend:latest
          labels: ${{ steps.meta-frontend.outputs.labels }}
      - name: Extract metadata (tags, labels) for Docker (api)
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
      - name: Build and push Docker image (api)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/prod.api.Dockerfile
          push: true
          pull: true
          tags: |
            ghcr.io/igalia/phpreport/api:latest
          labels: ${{ steps.meta-api.outputs.labels }}

